# Generated by Django 2.1 on 2019-05-16 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='카테고리 이름')),
                ('img', models.ImageField(blank=True, upload_to='category/', verbose_name='카테고리 이미지')),
            ],
        ),
    ]
