# Generated by Django 2.1 on 2019-06-24 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0011_auto_20190617_1520'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantTimelineComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(verbose_name='댓글')),
                ('is_active', models.BooleanField(default=True, verbose_name='댓글 활성화 여부')),
                ('restaurant_timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.RestaurantTimeline', verbose_name='해당 타임라인')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='댓글 작성자')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
