# Generated by Django 2.1 on 2019-05-16 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30, verbose_name='메뉴이름')),
                ('img', models.ImageField(blank=True, upload_to='menu/%Y/%m/%d', verbose_name='메뉴이미지')),
                ('detail', models.CharField(max_length=100, verbose_name='메뉴상세설명')),
                ('price', models.IntegerField(default=0, verbose_name='메뉴가격')),
                ('type', models.CharField(max_length=20, verbose_name='메뉴타입(인기메뉴,밥류...')),
                ('restaurant', models.ForeignKey(on_delete=True, to='restaurant.Restaurant', verbose_name='연관되는 레스토랑')),
                ('tastes', models.ManyToManyField(blank=True, to='accounts.Taste', verbose_name='characteristics of menu')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
