# Generated by Django 2.1 on 2019-05-20 04:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='hit',
            field=models.PositiveIntegerField(default=0, verbose_name='조회 수'),
        ),
        migrations.AddField(
            model_name='menu',
            name='like',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='메뉴에 좋아요를 누른 사람'),
        ),
        migrations.AddField(
            model_name='menu',
            name='score',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='점수'),
        ),
    ]
