# Generated by Django 2.1 on 2019-06-05 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0003_auto_20190524_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuTimeLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(1, '생성'), (2, '갱신'), (3, '삭제')], verbose_name='생성1,갱신2,삭제3')),
                ('prior_menu_img', models.ImageField(blank=True, upload_to='timeline/prior/menu/%Y/%m/%d', verbose_name='변경전 이미지')),
                ('prior_menu_detail', models.CharField(blank=True, max_length=100, verbose_name='변경 전 메뉴상세설명')),
                ('prior_menu_price', models.IntegerField(default=0, verbose_name='변경 전 메뉴가격')),
                ('post_menu_img', models.ImageField(blank=True, upload_to='timeline/post/menu/%Y/%m/%d', verbose_name='변경된 이미지')),
                ('post_menu_detail', models.CharField(blank=True, max_length=100, verbose_name='변경 후 메뉴상세설명')),
                ('post_menu_price', models.IntegerField(default=0, verbose_name='변경 후 메뉴가격')),
                ('is_recommended', models.BooleanField(blank=True, default=False, verbose_name='사장님 추천 메뉴인가?')),
                ('like', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='메뉴에 좋아요를 누른 사람')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Menu', verbose_name='모델 외래키')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
