# Generated by Django 2.1 on 2019-06-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menutimeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_group_purchase',
            field=models.BooleanField(default=False, verbose_name='메뉴 공구 허용 여부'),
        ),
        migrations.AddField(
            model_name='menu',
            name='max_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='최대 공구 가능 수량'),
        ),
        migrations.AddField(
            model_name='menu',
            name='min_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='최소 공구 가능 수량'),
        ),
    ]
