# Generated by Django 2.1 on 2019-06-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20190610_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='is_group_purchase',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='max_quantity',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='min_quantity',
        ),
        migrations.AddField(
            model_name='menu',
            name='is_set_menu',
            field=models.BooleanField(default=False, verbose_name='세트 메뉴 여부'),
        ),
        migrations.AddField(
            model_name='menu',
            name='is_yosigy',
            field=models.BooleanField(default=False, verbose_name='요식이 이벤트 여부'),
        ),
    ]
