# Generated by Django 2.1 on 2019-06-10 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0004_auto_20190610_1425'),
        ('menu', '0004_menutimeline'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateField(verbose_name='마감기한')),
                ('target_number', models.PositiveIntegerField(default=0, verbose_name='목표 인원')),
                ('status', models.IntegerField(choices=[(1, '진행 전'), (2, '진행 중'), (3, '완료')], verbose_name='공구 상태')),
                ('notice', models.TextField(blank=True, verbose_name='게시글')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Menu', verbose_name='공구할 메뉴')),
                ('participant', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='현재 참여자')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant', verbose_name='공구 제안한 레스토랑')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer', to=settings.AUTH_USER_MODEL, verbose_name='공구 글 작성자')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
