# Generated by Django 2.1 on 2019-05-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergiftcoupon',
            name='is_checked',
            field=models.BooleanField(default=False, verbose_name='받은 쿠폰 확인'),
        ),
    ]
