# Generated by Django 2.2 on 2019-04-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190410_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='udpated_date',
            new_name='updated_date',
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('p', 'Published'), ('w', 'Withdrawn'), ('d', 'Draft')], max_length=1),
        ),
    ]
