# Generated by Django 2.2 on 2019-04-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190410_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('w', 'Withdrawn'), ('p', 'Published')], max_length=1),
        ),
    ]
