# Generated by Django 2.1 on 2019-06-12 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0005_auto_20190610_1514'),
        ('restaurant', '0006_auto_20190610_1605'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Yosigy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateField(verbose_name='마감기한')),
                ('notice', models.TextField(blank=True, verbose_name='게시글')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant', verbose_name='공구 제안한 레스토랑')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='사장님')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='YosigyMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('discounted_price', models.PositiveIntegerField(default=0, verbose_name='할인된 메뉴 가격')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Menu', verbose_name='메뉴')),
                ('yosigy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yosigy.Yosigy', verbose_name='요시기')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
