# Generated by Django 2.1 on 2019-06-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yosigy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yosigy',
            name='min_price',
            field=models.PositiveIntegerField(default=0, verbose_name='최소 주문 금액'),
        ),
    ]
