# Generated by Django 2.1 on 2019-06-13 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20190613_1016'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yosigy', '0002_yosigy_min_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='YosigyTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('expire_time', models.DateTimeField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Menu', verbose_name='요시기 메뉴에 해당하는 메뉴')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='식권 주인')),
                ('yosigy_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yosigy.YosigyMenu', verbose_name='요시기 메뉴')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
