# Generated by Django 2.1 on 2019-06-18 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yosigy', '0004_yosigyticket_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('total_price', models.PositiveIntegerField(default=0, verbose_name='최종금액')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='티켓 구매자')),
                ('yosigy_ticket', models.ManyToManyField(to='yosigy.YosigyTicket', verbose_name='사용할 요식이 티켓')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
