# Generated by Django 2.1 on 2019-06-20 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_auto_20190613_1111'),
        ('yosigy', '0005_ticketpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketpayment',
            name='restaurant',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant', verbose_name='구매한 레스토랑'),
            preserve_default=False,
        ),
    ]
