# Generated by Django 2.1 on 2019-05-16 01:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='업체명')),
                ('owner', models.CharField(max_length=20, verbose_name='주인')),
                ('title', models.CharField(max_length=50, verbose_name='업체명+기타문구(x치킨-서초점)')),
                ('img', models.ImageField(blank=True, upload_to='restaurant/%Y/%m/%d', verbose_name='레스토랑 이미지')),
                ('tel', models.CharField(max_length=13, verbose_name='전화번호')),
                ('min_order_price', models.IntegerField(default=0, verbose_name='최소주문금액')),
                ('order_way', models.CharField(max_length=15, verbose_name='주문방식')),
                ('origin', models.TextField(verbose_name='원산지')),
                ('delivery_charge', models.IntegerField(default=0, verbose_name='배달요금')),
                ('info', models.TextField(verbose_name='사장님 알림말')),
                ('type', models.CharField(max_length=50, verbose_name='레스토랑타입(요기요등록음식점)')),
                ('estimated_delivery_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='배달예상시간')),
                ('operation_start_hour', models.DateTimeField(default=django.utils.timezone.now, verbose_name='영업시작시간')),
                ('operation_end_hour', models.DateTimeField(default=django.utils.timezone.now, verbose_name='영업종료시간')),
                ('category', models.ManyToManyField(to='category.Category', verbose_name='레스토랑에 관련된 카테고리')),
            ],
        ),
    ]
