# Generated by Django 2.1 on 2019-06-10 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import timeline.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0003_auto_20190520_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantTimeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(1, '생성'), (2, '갱신'), (3, '삭제')], default=timeline.models.TimelineStatus(2), verbose_name='상태')),
                ('changed_data', models.TextField(blank=True, verbose_name='변경 사항 내용')),
                ('changed_img', models.ImageField(blank=True, upload_to='timeline/%Y/%m/%d', verbose_name='변경 사진')),
                ('prior_info', models.CharField(blank=True, max_length=50, verbose_name='변경 전 정보')),
                ('post_info', models.CharField(blank=True, max_length=50, verbose_name='변경 후 정보')),
                ('timeline_type', models.IntegerField(choices=[(1, '사장님 알림'), (2, '이벤트'), (3, '운영시간'), (4, '기타 정보')], default=timeline.models.TimelineType(1), verbose_name='변경 사항')),
                ('changed_field', models.CharField(max_length=50, verbose_name='변경된 field')),
                ('like', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='좋아요를 누른 사람')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='restaurant',
            name='event',
            field=models.TextField(blank=True, verbose_name='이벤트'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='event_img',
            field=models.ImageField(blank=True, upload_to='restaurant/event/%Y/%m/%d', verbose_name='event image'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='like',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='레스토랑에 좋아요를 누른 사람'),
        ),
        migrations.AddField(
            model_name='restauranttimeline',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant', verbose_name='restaurant'),
        ),
    ]
