# Generated by Django 2.1 on 2019-06-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20190610_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='restauranttimeline',
            name='is_group_purchase',
            field=models.BooleanField(default=False, verbose_name='공구 허용 여부'),
        ),
    ]
