# Generated by Django 2.1 on 2019-06-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_auto_20190610_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='is_group_purchase',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_yosigy',
            field=models.BooleanField(default=False, verbose_name='요식이 이벤트 진행 여부'),
        ),
    ]
