# Generated by Django 2.1 on 2019-06-13 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0007_auto_20190612_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='store_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='store_owner', to=settings.AUTH_USER_MODEL, verbose_name='사장님 계정'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='owner',
            field=models.CharField(max_length=20, verbose_name='사장님 이름'),
        ),
    ]
