# Generated by Django 2.1 on 2019-06-17 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_restauranttimeline_yosigy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restauranttimeline',
            name='yosigy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yosigy.Yosigy', verbose_name='요식이 이벤트'),
        ),
    ]
