# Generated by Django 2.1 on 2019-06-17 06:20

from django.db import migrations, models
import timeline.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_auto_20190617_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restauranttimeline',
            name='timeline_type',
            field=models.IntegerField(choices=[(1, '사장님 알림'), (2, '이벤트'), (3, '운영시간'), (4, '기타 정보'), (5, '요식이 식권 이벤트')], default=timeline.models.TimelineType(1), verbose_name='변경 사항'),
        ),
    ]
