# Generated by Django 2.1 on 2019-05-16 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
        ('cart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='주문 식별번호')),
                ('total_price', models.IntegerField(default=0, verbose_name='주문 총 가격')),
                ('address', models.CharField(max_length=200, verbose_name='주문자 주소')),
                ('address_detail', models.CharField(max_length=200, verbose_name='주문자 상세 주소')),
                ('status', models.IntegerField(choices=[(0, '결제 진행 중'), (1, '결제 승인'), (2, '결제 취소')], default=0, verbose_name='주문 상태 정보')),
                ('is_delivery_completed', models.BooleanField(default=False, verbose_name='배달완료 여부')),
                ('weather', models.PositiveSmallIntegerField(default=0, verbose_name='주문 당시 날씨 정보')),
                ('phone_num', models.CharField(max_length=13, verbose_name='전화번호')),
                ('payment_status', models.IntegerField(choices=[(0, '현장결제 - 현금'), (1, '현장결제 - 카드')], default=0, verbose_name='주문 결제 상태 정보')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Cart', verbose_name='주문표')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant', verbose_name='해당 주문관련 레스토랑')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='주문자')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
