# Generated by Django 2.1 on 2019-05-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_gift_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_delivery_completed',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.IntegerField(choices=[(0, '대기 중'), (1, '배달 중'), (2, '배달 완료')], default=0, verbose_name='배달 상태 정보'),
        ),
    ]
