# Generated by Django 2.1 on 2019-06-13 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yosigy', '0003_yosigyticket'),
        ('order', '0003_auto_20190529_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='yosigy_ticket',
            field=models.ManyToManyField(blank=True, to='yosigy.YosigyTicket', verbose_name='사용한 요시기 식권'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.Cart', verbose_name='주문표'),
        ),
    ]
